name: 'xdg-validator-action'
description: 'Validates freedesktop.org files'
author: 'plfiorini'

branding:
  icon: 'check-circle'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  strict:
    description: 'Whether you want to perform a strict validation'
    default: false
